services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: laravel-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

